package server

import (
	"net/http"

	_ "github.com/superboomer/maptile/app/docs" // docs are generated by Swag CLI, you have to import it.
	"github.com/superboomer/maptile/app/server/api"
	"github.com/superboomer/maptile/app/server/middleware"
	httpSwagger "github.com/swaggo/http-swagger"
)

// SetRoutes create router
func (s *Server) SetRoutes(a *api.API, md *middleware.MD) {
	h := http.NewServeMux()

	h.HandleFunc("/map", a.Map)
	h.HandleFunc("/healthcheck", a.HealthCheck)
	h.HandleFunc("/provider", a.Provider)

	if s.options.Swagger {
		s.logger.Info("http swagger enabled")
		h.HandleFunc("/swagger/", httpSwagger.Handler(httpSwagger.URL("http://localhost:8080/swagger/doc.json")))
	}

	m := md.Log(md.RequestID(h))

	s.server.Handler = m
}
