definitions:
  api.healthCheckModel:
    properties:
      body:
        type: string
      status:
        type: integer
    type: object
  api.mapErrorModel:
    properties:
      body:
        type: string
      status:
        type: integer
    type: object
  api.providerModel:
    properties:
      key:
        type: string
      max_zoom:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: This is a easy HTTP API which provide map tiles
  title: Map Satellite provider
  version: 1.0.0
paths:
  /healthcheck:
    get:
      consumes:
      - application/json
      description: just return HealthCheckModel with API status (always return 200)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Request-Id:
              description: request_id
              type: string
          schema:
            $ref: '#/definitions/api.healthCheckModel'
      summary: handler for health check
  /map:
    get:
      consumes:
      - text/plain
      description: return merged satellite tiles in one image
      parameters:
      - description: Map provider
        in: query
        name: provider
        required: true
        type: string
      - description: latitude
        in: query
        name: lat
        required: true
        type: number
      - description: longitude
        in: query
        name: long
        required: true
        type: number
      - description: zoom of image
        in: query
        name: zoom
        required: true
        type: integer
      - default: 3
        description: count of tile of result image square
        in: query
        maximum: 10
        minimum: 1
        name: side
        type: integer
      produces:
      - image/jpeg
      responses:
        "200":
          description: OK
          headers:
            X-Request-Id:
              description: request_id
              type: string
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.mapErrorModel'
      summary: handler for generating satellite map for specified lat long and from
        specified vendor
  /provider:
    get:
      consumes:
      - text/plain
      description: reutrn JSON array with avalible provders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Request-Id:
              description: request_id
              type: string
          schema:
            items:
              $ref: '#/definitions/api.providerModel'
            type: array
      summary: handler return all registered providers
swagger: "2.0"
